name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: wasm32-unknown-unknown
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install Sass
        run: npm install -g sass
          
      - name: Install Cargo Generate
        run: cargo install cargo-generate --locked
          
      - name: Install Cargo Leptos
        run: cargo install cargo-leptos@^0.2 --locked
      - name: Install dependencies
        run: cd end2end && npm install
        
      - name: Run end-to-end tests
        run: cargo leptos end-to-end
